kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ratingsdb-mongodb
  namespace: db
spec:
  storageClassName: managed-premium
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi